### ISSUE TITLE
hover_layer and earase typos

### ISSUE THREAD

**Issue by troynall** [JanisQu/Godot-Tile-Pattern-Editor#1]
please use this corrected code ->

@onready var hover_layer: TileMapLayer = %HoverLayer

and

you mispelled "erase" throughout your code 
i think you mispelled as "earase" ?

other than that, your code works...

thanks,
troy

**Comment by JanisQu** [comment]
Thanks for Feedback!
I completely missed that. 
It Should be fixed now.
